[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1yp-1Zswwwf3ZjNWGrks0R3OFqZWlF30jwAwb-PZV1XM"
worksheet = "<worksheet-gid-or-folder-id>"  # Ensure this is correctly set

type = "service_account"
project_id = "talabat-441608"
private_key_id = "3c3d9df385ebb4960ba0e2b166d655118719c897"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+rdMbxx3FOsji
XVbOGoTyO90JHtdGElVpbUO6NawPGVJpwAajpd60sOLrz4xuTM2QH5y/IAoajVQk
ipTxh3Ul/sb6aJEkIv7sXRuqlvClIXZsXj/oMpCnFL7NR1MQ4fs4tNKOEEpSnext
l/jpZIaFU655nVF5f9H1K/fCuz+Ny4FrmPwxXsheAcpfNjc7zZ9Hi+0X7QcxqIKg
34NTUiHAJ3GOCyXghW7gAEwOIs2obPTDd8wAB5ju0z8OXTWJwMr0uCCWA+OauI7U
yx9OMiAQ8ABgKsV1IrzHxmiYKf/N/f3lF2Lfqo37/PHrm8yu6BET/+0eefrsKNAW
kR9FaYk1AgMBAAECggEACtSfwZupPrssjuMDW7iY5ZNt5ic4zhObg13/81M6Hy9u
hXAxUFlLEZNciE1lKhy1rmKFSjvdJw3xAhRXCnMJves/TRjkaZuNREqzmBhzucVx
Tw15bsx0d/EPN2S+PJ7BYMKwlP4q4o9yzvTLYCJkG62ZovHDH3YZrGXfcFGndfvI
jg3QoYBzo9/OVP9IvlwcS3kf8C+8O2OCCvlMeNc1UvxYJDvX8NkDiaigKY5F+y3Y
I44kF7vUk7LWYnELgtocCuAxiEB9ldKjZbCOt8ZDIb2ZpG26HKqVYMymUY7wCP/v
9YB6jN4/2AVSVx9OyMwXXdcCy7ujpqECD7cWbVEPYQKBgQDpwlqP/9lf+tuYQpP8
b06QVPgB1fZOHguQxNOsTdNgu8RvFbnok6OOMnuouHh3I5Q26KB9l4co4EK99VbC
0POrZ45+XoDal1sXcrwsvKj8XNazR7XXUCZi3Q5X4zRp9IVuYF7nMhGleNsHqfap
rzljX9B81GwwNgMt4fpKCBRu8QKBgQDQ0ivpGBrEwjqSeTnRmotSyM4SKSAg8liF
t+sBaMDvSWMJCEGMM65OqkZPNxnhyJBNzKesFTmvdjVO6P5WHsfEMK8OQoN+UJ0q
4xw6CHn7Xn9UuiV2a+jaAsl0yeq2je2K+9YV34nvnIgv5BJrlE4UEv6aFdOnad56
GLoIr9ZGhQKBgEfFjrzL11gq06WqO3m0SzDxhbw6j4donjBy3nL26kG3JRbeWthY
DE2qnmEtUn9yAx3gyvYEwlEAmj1syJjEQyyLfSq7pWB4PFW0uqYZvuDNOHaPO/vB
9idArBi7/+nQU++R01G1A8oEk2uE+eEblck3L/JD3nvm+Y7q5Ug5ttxhAoGAGtdp
HYUjq7broHhEnlSnI/T7yAnRP2rnRgjmBEBazGc6e6a8BjF+bk4ky3nhscv+AIIV
62CvEYa4Q3RffOJn+yfm2IZkMJBcI28d6be9NjpnU5S5zAcC30MMch6iNOT5a6wD
ULxzFoGgX8eJNprRjnMClvvHQPWyyy7yertfZ6ECgYAjQ/zBeKTOjAUbbh/Y/W8P
ZzaDrc07czpO9n5DWnwEVDn997Ewad1dyVTCyNVpFeQxG4GYleVsUOa0N8enSl8A
9K1ZZnGv4LVKALhcwUo5nMKOnW6LAOa2JR63nCvRIlGgPFcMi5cwyJZRs64ohr1J
ULARC3pre1OorOkuc3fEpQ==
-----END PRIVATE KEY-----
"""
client_email = "talabat@talabat-441608.iam.gserviceaccount.com"
client_id = "110578508839591344150"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/talabat%40talabat-441608.iam.gserviceaccount.com"
